Fix plain text password fill prevention
keepassxreboot/keepassxc-browser pull request #2259
Opened 2024-07-03 07:56 UTC by varjolintu

Regression from https://github.com/keepassxreboot/keepassxc-browser/pull/2107.

The password fill should be prevented at the last part of the fill, inside `kpxcFill.fillInCredentials()`. It should be also checked if the element is actually an input field. If not, we just don't even try to fill the password.

Fixes #2135.

2024-07-03 10:12 UTC, droidmonkey requested changes

2024-07-03 10:12 UTC, droidmonkey commented on keepassxc-browser/content/fill.js
> +            kpxcUI.createNotification('warning', tr('fieldsPasswordFillNotAccepted'));
The above check is an error and allowed to proceed. This one is a warning and stopped. Those need to be swapped in this case (the error and warning attributes).

2024-07-03 22:36 UTC, droidmonkey approved these changes

2024-07-04 04:56 UTC, merged

2024-08-15 07:53 UTC, CharlemagneLasse commented
This change breaks the XHTML pages (password fields will not be filled out because the `nodeName` is `input` and not `INPUT`). See #2313

2024-08-15 08:03 UTC, varjolintu commented
> This change breaks the XHTML pages (password fields will not be filled out because the `nodeName` is `input` and not `INPUT`). See #2313

This is not why XHTML pages break. See the explanation in the bug you opened.